"""
Deterministic multi-signal scoring engine.

Takes outputs from all data fetchers and returns a scored candidate list.
Claude is NOT involved here — all scoring is rule-based and auditable.
"""

from __future__ import annotations

SHORT_TERM_WEIGHTS = {
    "fundamental_strong": 2,        # ROE>15% & D/E<1 & EPS-growth>0 (yfinance .info)
    "bulk_deal_fii_dii": 3,
    "actual_52w_breakout": 3,      # price broke through prior 52w high
    "delivery_surge": 2,           # DELIV_PER >= 50% on EQ series — institutional accumulation
    "rsi_bearish_div": 3,          # price HH + RSI LH: data shows +1.04 lift over 15k trades
    "rsi_momentum": 2,             # RSI 50-75: momentum building
    "rs_quality_strong": 2,        # ATR-adjusted RS: (stock_20d − nifty_20d) / ATR% > 5.0
    "rs_vs_nifty": 1,              # stock outperforming Nifty by 2%+ over 20d
    "options_pcr_fear": 1,         # PCR > 1.5: extreme fear = contrarian bullish (min OI required)
    "options_long_buildup": 1,     # price up + OI up = fresh longs (min OI required)
    "options_short_covering": 1,   # price up + OI down = shorts exiting = bullish (min OI required)
    "fo_ban_lifted": 1,            # just removed from NSE F&O ban: liquidity restored, fresh positions allowed
    "weekly_trend_aligned": 1,     # weekly EMA10 > EMA20: daily signal aligns with larger timeframe
    "sector_in_momentum": 1,       # stock is in a top-2 performing NSE sector index (5d return)
}

SWING_WEIGHTS = {
    "results_due": 1,               # upcoming results — informational flag only (PEAD needs actual beat)
    "promoter_buying": 3,           # sets timeframe → 5-7d
    "sast_insider_buying": 3,       # SEBI SAST filing: entity acquiring ≥5% stake — creeping accumulation
    "consolidation_breakout": 3,
    "results_beat_announced": 3,    # post-3:30 PM filing: quarterly result filed (potential beat)
    "buyback_announced": 2,         # board-approved buyback = promoter confidence, floor under price
    "contract_win": 2,              # order/contract receipt — high-impact for mid/small caps
    "dividend_announced": 1,        # dividend declared = shareholder reward signal
}

DISQUALIFIER_WEIGHTS = {
    "fundamental_weak": -2,          # net loss or D/E>3 (yfinance .info); missing data → neutral
    "f_group": -5,                 # currently on NSE F&O ban list: liquidity risk, forced-exit danger
    "rsi_bullish_div": -5,         # price LL + RSI HL: false bottoms — data shows −1.63 lift over 253 trades
    "thin_market_extreme": -4,     # avg daily turnover < ₹1cr: unreliable signals + exit risk
    "thin_market_light": -2,       # avg daily turnover ₹1cr–₹5cr: reduced liquidity, higher spread
    "options_short_buildup": -2,   # price down + OI up = fresh shorts entering
    "distribution_signal": -1,     # volume spike + price DOWN = institutional selling
    "volume_5x": -1,               # raw volume surge at entry: data shows −0.25 lift (noise, not edge)
    "bb_squeeze_breakout": -1,     # BB squeeze at entry: exhaustion signal, −0.18 lift
    "macd_bearish_cross": -1,      # histogram / zero-line crossed down in last 3-5 bars
    "bullish_candle": -1,          # bullish candle at entry predicts underperformance (−0.43 lift)
    "bearish_candle": -1,          # shooting_star / bearish_engulfing / bearish_marubozu on last bar
    "options_pcr_greed": -1,       # PCR < 0.5: extreme complacency (min OI required)
    "options_long_unwinding": -1,  # price down + OI down = longs exiting (min OI required)
}

# Regime-dependent overrides for SHORT_TERM_WEIGHTS.
# Generated by: python scripts/calibrate_weights.py --by-regime
# None = fall back to SHORT_TERM_WEIGHTS for that bucket.
REGIME_WEIGHTS: dict[str, dict[str, int] | None] = {
    "uptrend":   None,
    "ranging":   None,
    "downtrend": None,
}

# Lowered to 2 to prevent dropping single-signal stocks before Pass 2 options/SAST fetch
MIN_SCORE = 2
MIN_SIGNALS = 1
PENNY_THRESHOLD = 10.0  # ₹10


def _build_signal_map(
    ticker: str,
    bulk_deals: list[dict],
    volume_data: dict | None,
    fo_ban_removed: list[str],
    results_calendar: list[dict],
    breakout_data: dict | None,
    promoter_data: dict | None = None,
    options_data: dict | None = None,
    technical_data: dict | None = None,
    delivery_data: dict | None = None,
    fo_ban_current: set[str] | None = None,
    announcements_data: dict | None = None,
    hot_sector_tickers: set[str] | None = None,
    sast_data: bool = False,
    fundamental_data: dict | None = None,
) -> dict[str, bool]:
    """Build a boolean signal map for a single ticker."""
    signals: dict[str, bool] = {k: False for k in list(SHORT_TERM_WEIGHTS) + list(SWING_WEIGHTS) + list(DISQUALIFIER_WEIGHTS)}

    # --- DISQUALIFIERS computed early (can short-circuit scoring logic) ---

    # F&O ban: ticker is currently on NSE's banned list — position-building is prohibited,
    # exits can be forced at unfavourable prices, and signals from this stock are unreliable.
    signals["f_group"] = ticker in (fo_ban_current or set())

    # F&O ban lifted: ticker was just removed from the ban — liquidity restored, fresh derivative
    # positions are now allowed. Pent-up institutional demand often causes a near-term price pop.
    signals["fo_ban_lifted"] = ticker in set(fo_ban_removed)

    # --- SHORT-TERM signals ---

    # Bulk/block deal by known FII/DII
    ticker_deals = [d for d in bulk_deals if d["ticker"] == ticker and d["is_fii_dii"]]
    signals["bulk_deal_fii_dii"] = bool(ticker_deals)

    # Volume ≥ 2.5× 30-day average
    if volume_data:
        signals["volume_5x"]          = volume_data.get("is_volume_surge", False)
        signals["distribution_signal"] = volume_data.get("is_distribution", False)
        # Thin market: avg daily turnover < ₹5 crore — signal quality is unreliable
        avg_30d = volume_data.get("avg_30d_volume", 0) or 0
        price   = volume_data.get("today_close", 0) or 0
        daily_turnover = avg_30d * price if (avg_30d > 0 and price > 0) else 0
        signals["thin_market_extreme"] = bool(0 < daily_turnover < 1e7)    # < ₹1cr
        signals["thin_market_light"]   = bool(1e7 <= daily_turnover < 5e7) # ₹1cr–₹5cr

    # 52-week high: only actual breakout scores; proximity alone removed (redundant + noisy)
    if breakout_data:
        signals["actual_52w_breakout"]    = breakout_data.get("actual_breakout", False)
        signals["consolidation_breakout"] = breakout_data.get("consolidation_breakout", False)

    # Options signals — PCR only at extremes; long_buildup gated by min OI in options.py
    if options_data:
        signals["options_pcr_fear"]        = options_data.get("pcr_fear", False)
        signals["options_pcr_greed"]       = options_data.get("pcr_greed", False)
        signals["options_long_buildup"]    = options_data.get("long_buildup", False)
        signals["options_short_buildup"]   = options_data.get("short_buildup", False)
        signals["options_short_covering"]  = options_data.get("short_covering", False)
        signals["options_long_unwinding"]  = options_data.get("long_unwinding", False)

    # Technical signals (pass 3 only — after enrich_candidate_context)
    if technical_data:
        signals["rsi_momentum"]        = technical_data.get("rsi_momentum", False)
        signals["rs_vs_nifty"]         = technical_data.get("rs_vs_nifty", False)
        signals["rsi_bearish_div"]     = technical_data.get("rsi_bearish_div", False)
        signals["rsi_bullish_div"]     = technical_data.get("rsi_bullish_div", False)
        signals["macd_bearish_cross"]  = technical_data.get("macd_bearish_cross", False)
        signals["bb_squeeze_breakout"] = technical_data.get("bb_squeeze_breakout", False)
        signals["bullish_candle"]       = technical_data.get("bullish_candle", False)
        signals["bearish_candle"]       = technical_data.get("bearish_candle", False)
        signals["weekly_trend_aligned"] = technical_data.get("weekly_trend_aligned", False)
        signals["rs_quality_strong"]    = technical_data.get("rs_quality_strong", False)

    # Delivery volume signal from NSE bhav copy
    if delivery_data:
        signals["delivery_surge"] = delivery_data.get("delivery_surge", False)

    # Corporate announcements filed post-3:30 PM (pre-market alpha)
    if announcements_data:
        ann = announcements_data.get(ticker, {})
        signals["results_beat_announced"] = ann.get("results_beat_announced", False)
        signals["buyback_announced"]      = ann.get("buyback_announced", False)
        signals["contract_win"]           = ann.get("contract_win", False)
        signals["dividend_announced"]     = ann.get("dividend_announced", False)

    # Sector rotation: ticker is in top-2 performing NSE sector index (5d return)
    signals["sector_in_momentum"] = ticker in (hot_sector_tickers or set())

    # --- SWING signals ---

    # Upcoming results — weak informational flag; real PEAD requires confirmed post-beat data
    ticker_results = [r for r in results_calendar if r["ticker"] == ticker]
    if ticker_results:
        signals["results_due"] = True

    # Promoter / insider buying
    if promoter_data:
        signals["promoter_buying"] = promoter_data.get("promoter_bought", False)

    # SAST filing: SEBI mandatory disclosure for creeping acquisitions ≥5% stake
    signals["sast_insider_buying"] = bool(sast_data)

    # Fundamental quality from yfinance .info (soft gate — missing data → neutral)
    if fundamental_data:
        signals["fundamental_strong"] = bool(fundamental_data.get("fundamental_strong", False))
        signals["fundamental_weak"]   = bool(fundamental_data.get("fundamental_weak",   False))

    return signals


def _compute_score(
    signals: dict[str, bool],
    market_regime: str = "normal",
    nifty_trend: str = "ranging",
) -> tuple[int, str]:
    score = 0
    timeframe = "1-2d"

    # Select SHORT_TERM_WEIGHTS override for this Nifty trend regime (if calibrated)
    short_term = REGIME_WEIGHTS.get(nifty_trend) or SHORT_TERM_WEIGHTS

    for sig, weight in short_term.items():
        if signals.get(sig):
            # RSI 50-70 produces false signals in high-volatility regimes; disable it
            if sig == "rsi_momentum" and market_regime == "high_vol":
                continue
            score += weight

    for sig, weight in SWING_WEIGHTS.items():
        if signals.get(sig):
            score += weight
            if sig in ("results_due", "promoter_buying"):
                timeframe = "5-7d"

    for sig, weight in DISQUALIFIER_WEIGHTS.items():
        if signals.get(sig):
            score += weight  # weights are already negative

    return score, timeframe


def _active_signals(signals: dict[str, bool]) -> list[str]:
    return [sig for sig, active in signals.items() if active and sig not in DISQUALIFIER_WEIGHTS]


def _disqualifiers(signals: dict[str, bool]) -> list[str]:
    return [sig for sig, active in signals.items() if active and sig in DISQUALIFIER_WEIGHTS]


def score_candidates(
    bulk_deals: list[dict],
    volume_gainers: list[dict],
    fo_ban_removed: list[str],
    results_calendar: list[dict],
    breakouts: list[dict],
    promoter_signals: dict | None = None,
    options_signals: dict | None = None,
    technical_signals: dict | None = None,
    delivery_signals: dict | None = None,
    fo_ban_current: set[str] | None = None,
    market_regime: str = "normal",
    announcements: list[dict] | None = None,
    hot_sector_tickers: set[str] | None = None,
    sast_signals: dict[str, bool] | None = None,
    breadth_label: str = "neutral",
    nifty_trend: str = "ranging",
    fundamental_signals: dict[str, dict] | None = None,
) -> list[dict]:
    """
    Score every unique ticker across all data sources and return qualifying candidates.

    market_regime:       "low_vol" | "normal" | "high_vol" — high_vol applies -1 to all scores.
    breadth_label:       "strong" | "neutral" | "weak" — weak applies -1 (stacks with high_vol).
    nifty_trend:         "uptrend" | "ranging" | "downtrend" — selects REGIME_WEIGHTS override.
    fundamental_signals: {ticker: {fundamental_strong, fundamental_weak, ...}} from fundamentals.py
    """
    # Collect all unique tickers across all data sources
    all_tickers: set[str] = set()
    all_tickers.update(d["ticker"] for d in bulk_deals)
    all_tickers.update(d["ticker"] for d in volume_gainers)
    all_tickers.update(fo_ban_removed)  # ban-lifted tickers enter scoring universe
    all_tickers.update(r["ticker"] for r in results_calendar)
    all_tickers.update(b["ticker"] for b in breakouts)

    # Build lookup dicts for O(1) access
    volume_map: dict[str, dict] = {d["ticker"]: d for d in volume_gainers}
    breakout_map: dict[str, dict] = {b["ticker"]: b for b in breakouts}

    # Build announcements lookup: {ticker: {signal_key: True, ...}}
    # A ticker can have multiple announcements; last one per signal_key wins (all are True anyway).
    ann_map: dict[str, dict] = {}
    for ann in (announcements or []):
        t = ann.get("ticker", "")
        if t:
            all_tickers.add(t)  # announced ticker enters universe even without price data
            ann_map.setdefault(t, {})[ann.get("signal_key", "")] = True

    candidates = []
    for ticker in all_tickers:
        vol  = volume_map.get(ticker)
        brk  = breakout_map.get(ticker)
        prom = (promoter_signals or {}).get(ticker)
        opts = (options_signals or {}).get(ticker)
        tech = (technical_signals or {}).get(ticker)
        deliv = (delivery_signals or {}).get(ticker)
        ann   = ann_map.get(ticker)
        sast  = bool((sast_signals or {}).get(ticker, False))
        fund  = (fundamental_signals or {}).get(ticker)

        signals = _build_signal_map(
            ticker, bulk_deals, vol, fo_ban_removed, results_calendar, brk,
            promoter_data=prom, options_data=opts, technical_data=tech,
            delivery_data=deliv, fo_ban_current=fo_ban_current,
            announcements_data={ticker: ann} if ann else None,
            hot_sector_tickers=hot_sector_tickers,
            sast_data=sast,
            fundamental_data=fund,
        )

        score, timeframe = _compute_score(signals, market_regime, nifty_trend)

        # High-volatility regime: all signals are noisier — reduce score by 1
        if market_regime == "high_vol":
            score = max(0, score - 1)
        # Weak breadth: market internals deteriorating — reduce score by 1 (stacks with high_vol)
        if breadth_label == "weak":
            score = max(0, score - 1)

        active = _active_signals(signals)
        disqs = _disqualifiers(signals)

        if score < MIN_SCORE or len(active) < MIN_SIGNALS:
            continue

        today_close = (vol or brk or {}).get("today_close")
        is_penny = today_close is not None and today_close < PENNY_THRESHOLD

        candidates.append({
            "ticker": f"[PENNY]{ticker}" if is_penny else ticker,
            "score": score,
            "active_signals": active,
            "disqualifiers": disqs,
            "timeframe": timeframe,
            "today_close": today_close,
            "volume_ratio": (vol or {}).get("volume_ratio"),
            "market_cap_cr": (vol or {}).get("market_cap_cr"),
            "52w_high": (brk or {}).get("52w_high"),
            "consolidation_breakout": signals.get("consolidation_breakout", False),
            "promoter_pct": (prom or {}).get("promoter_pct"),
            "promoter_bought": (prom or {}).get("promoter_bought", False),
            "options_pcr": (opts or {}).get("pcr"),
            "delivery_pct": (deliv or {}).get("delivery_pct"),
            "delivery_spike_pp": (deliv or {}).get("delivery_spike_pp"),
            # Pass through raw deal info for LLM context
            "bulk_deals": [d for d in bulk_deals if d["ticker"] == ticker],
            "upcoming_results": [r for r in results_calendar if r["ticker"] == ticker],
        })

    candidates.sort(key=lambda x: x["score"], reverse=True)
    print(f"[scorer] {len(all_tickers)} tickers evaluated, {len(candidates)} qualified")
    return candidates
